InternshipAutomationSystem/Areas/Student/Controllers/ApplicationController.cs
using Internship.DataAccess.Data;
using Internship.DataAccess.Repository;
using Internship.DataAccess.Repository.IRepository;
using Internship.Models;
using Internship.Models.ViewModels;
using Internship.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using SendGrid.Helpers.Mail;
using System.Security.Claims;

namespace InternshipAutomationSystem.Areas.Student.Controllers
{
    [Area("Student")]
    [Authorize(Roles = SD.Role_User_Student)]
    public class ApplicationController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _HostEnvironment;
        private readonly PdfGenerator _pdfGenerator;
        private readonly ApplicationDbContext _dbContext;

        public ApplicationController(IUnitOfWork unitOfWork, IWebHostEnvironment hostEnvironment, PdfGenerator pdfGenerator, ApplicationDbContext dbContext, UserManager<ApplicationUser> userManager)
        {
            _pdfGenerator = pdfGenerator;
            _dbContext = dbContext;
            _unitOfWork = unitOfWork;
            _userManager = userManager;
            _HostEnvironment = hostEnvironment;
        }
        [HttpGet]
        public IActionResult SubmitForm(int? Id)
        {
            string studentId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            ApplicationForm applicationForm = _dbContext.ApplicationForms.FirstOrDefault(f => f.Student.UserId == studentId);

            if (applicationForm != null)
            {
               
                return RedirectToAction("AlreadySubmitted");
            }

            ApplicationVM ApplicationVM = new()
            {
                ApplicationForms = new(),

                StudentList = _unitOfWork.Students.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.StudentId.ToString()
                }),

                CoordinatorList = _unitOfWork.Coordinators.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                })



            };

            if (Id == null || Id == 0)
            {
                return View(ApplicationVM);
            }
            else
            {
                ApplicationVM.ApplicationForms = _unitOfWork.Applications.GetFirstOrDefault(u => u.Id == Id);
                return View(ApplicationVM);
            }
        }


        public IActionResult Success()
        {
            return View();
        }



        [HttpPost]
        [ValidateAntiForgeryToken]

        public IActionResult SubmitForm(ApplicationVM obj)
        {
            ApplicationUser user = _userManager.GetUserAsync(User).Result;

            Student_User studentUser = _dbContext.Students.FirstOrDefault(s => s.UserId == user.Id);
            obj.ApplicationForms.StudentId = studentUser.StudentId;
            obj.ApplicationForms.InternshipCoordinatorId = studentUser.CoordinatorId;

            string studentId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            ApplicationForm applicationForm = _dbContext.ApplicationForms.FirstOrDefault(f => f.Student.UserId == studentId);

            if (ModelState.IsValid)
            {
             
                _dbContext.ApplicationForms.Add(obj.ApplicationForms);
                _dbContext.SaveChanges();
                _pdfGenerator.GeneratePdf(obj.ApplicationForms);

            }
            var student = _dbContext.Students.FirstOrDefault(s => s.StudentId == obj.ApplicationForms.StudentId);
            if (student != null)
            {
                Student_User studentUser2 = _dbContext.Students
                          .Include(s => s.User)
                          .FirstOrDefault(s => s.UserId == obj.ApplicationForms.Student.UserId);

                if (studentUser2.User.Status == "notyet" || studentUser2.User.Status == null)
                {
                    studentUser2.User.Status = "filled";
                }
                else
                {
                    return NotFound();
                }

                _dbContext.SaveChanges();
            }
            return RedirectToAction("SubmitedForms");

            return View(obj.ApplicationForms);
        }

        public IActionResult SubmitedForms()
        {
            // Retrieve the submitted application form data from the database
            var lastSubmittedForm = _dbContext.ApplicationForms.OrderByDescending(f => f.Id).FirstOrDefault();

            // Display the success page and pass the retrieved form data to the view
            return View(lastSubmittedForm);
        }

        public IActionResult DownloadApplicationForm(int id)
        {
            string studentId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            ApplicationForm applicationForm = _dbContext.ApplicationForms.FirstOrDefault(f => f.Student.UserId == studentId);
           


            if (applicationForm == null)
            {
                // Return an error message or redirect to an error page if the application form is not found
                return RedirectToAction("SubmitForm");
            }
            string studentName = applicationForm.Name;
            string studentID = applicationForm.SID;
            // Generate the PDF for the application form
            PdfGenerator pdfGenerator = new PdfGenerator(_HostEnvironment);
            pdfGenerator.GeneratePdf(applicationForm);

            // Get the file path of the generated PDF
            string wwwrootPath = _HostEnvironment.WebRootPath;
            string filePath = Path.Combine(wwwrootPath, "PDF", "hello.pdf");

            // Read the file contents into a byte array
            byte[] fileBytes = System.IO.File.ReadAllBytes(filePath);

            // Set the content type and file name for the response
            string contentType = "application/pdf";
            string fileName =  studentName+" "+ studentID + ".pdf";

            // Return the file as a downloadable response
            return File(fileBytes, contentType, fileName);
        }
        public IActionResult AlreadySubmitted()
        {
            return View();
        }






        public IActionResult ApplicationForm_Final_Upsert(int? Id)
        {

            FinalApplicationVM FinalApplicationVM = new()
            {
                SubmittedApplicationForms = new(),

                StudentList = _unitOfWork.Students.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.StudentId.ToString(),
                    Selected = i.submittedApplicationFormId != null
                }),

                CoordinatorList = _unitOfWork.Coordinators.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                })

            };


            if (Id == null || Id == 0)
            {
                return View(FinalApplicationVM);
            }

            else
            {
                FinalApplicationVM.SubmittedApplicationForms = _unitOfWork.SubmittedApplicationForms.GetFirstOrDefault(u => u.Id == Id);
                return View(FinalApplicationVM);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ApplicationForm_Final_Upsert(FinalApplicationVM obj, IFormFile file)
        {
            ApplicationUser user2 = _userManager.GetUserAsync(User).Result;

            Student_User studentUser = _dbContext.Students.FirstOrDefault(s => s.UserId == user2.Id);
            obj.SubmittedApplicationForms.StudentId = studentUser.StudentId;
            obj.SubmittedApplicationForms.InternshipCoordinatorId = studentUser.CoordinatorId;

            if (ModelState.IsValid)
            {
                var user = _userManager.GetUserAsync(User).GetAwaiter().GetResult();

                string wwwRootPath = _HostEnvironment.WebRootPath;

                if (file != null)
                {
                    string fileName = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(wwwRootPath, @"PDFCAN\Forms");
                    var extension = Path.GetExtension(file.FileName);

                    if (obj.SubmittedApplicationForms.PDFForm != null)
                    {
                        var oldFilePath = Path.Combine(wwwRootPath, obj.SubmittedApplicationForms.PDFForm.TrimStart('\\'));
                        if (System.IO.File.Exists(oldFilePath))
                        {
                            System.IO.File.Delete(oldFilePath);
                        }
                    }
                    using (var fileStream = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                    {
                        file.CopyTo(fileStream);
                    }
                    obj.SubmittedApplicationForms.PDFForm = @"PDFCAN\Forms\" + fileName + extension;

                    // Update the Status property for the student
                    var student = _dbContext.Students.FirstOrDefault(s => s.StudentId == obj.SubmittedApplicationForms.StudentId);
                    if (student != null)
                    {
                       if(student.ApplicationFormStatus.ToLower() == "n/a")
                        {
                            student.ApplicationFormStatus = "pending";
                        }
                        else
                        {
                            return NotFound();
                        }

InternshipAutomationSystem/Areas/Student/Controllers/OfficialletterController.cs
using Internship.DataAccess.Data;
using Internship.DataAccess.Repository.IRepository;
using Internship.Models;
using Internship.Models.ViewModels;
using Internship.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace InternshipAutomationSystem.Areas.Student.Controllers
{
    [Area("Student")]
    [Authorize(Roles = SD.Role_User_Student)]
    public class OfficialletterController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _HostEnvironment;
        private readonly PdfGenerator _pdfGenerator;
        private readonly ApplicationDbContext _dbContext;

        public IActionResult Index()
        {
            return View();
        }

        public OfficialletterController(IUnitOfWork unitOfWork, IWebHostEnvironment hostEnvironment, PdfGenerator pdfGenerator, ApplicationDbContext dbContext, UserManager<ApplicationUser> userManager)
        {
            _pdfGenerator = pdfGenerator;
            _dbContext = dbContext;
            _unitOfWork = unitOfWork;
            _userManager = userManager;
            _HostEnvironment = hostEnvironment;
        }

        public IActionResult Letter_Upsert(int? Id)
        {

            OfficialLetterVM OfficialLetterVM = new()
            {
                OfficialLetters = new(),

                StudentList = _unitOfWork.Students.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.StudentId.ToString(),
                    Selected = i.HealthInsuranceId != null
                }),
                CoordinatorList = _unitOfWork.Coordinators.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString(),

                }),

            };


            if (Id == null || Id == 0)
            {
                return View(OfficialLetterVM);
            }

            else
            {
                OfficialLetterVM.OfficialLetters = _unitOfWork.OfficialLetters.GetFirstOrDefault(u => u.Id == Id);
                return View(OfficialLetterVM);
            }
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Letter_Upsert(OfficialLetterVM obj)
        {
            ApplicationUser user = _userManager.GetUserAsync(User).Result;

            Student_User studentUser = _dbContext.Students.FirstOrDefault(s => s.UserId == user.Id);
            obj.OfficialLetters.StudentId = studentUser.StudentId;
            obj.OfficialLetters.InternshipCoordinatorId = studentUser.CoordinatorId;
            var Student = _unitOfWork.Students.GetFirstOrDefault(u => u.StudentId == obj.OfficialLetters.StudentId);
            var InternshipCoordinator = _unitOfWork.Coordinators.GetFirstOrDefault(u => u.Id == obj.OfficialLetters.InternshipCoordinatorId);
        

            if (ModelState.IsValid)
            {
               

                if (obj.OfficialLetters.Id == 0)
                {
                    _unitOfWork.OfficialLetters.Add(obj.OfficialLetters);
                }
                else
                {
                    _unitOfWork.OfficialLetters.Update(obj.OfficialLetters);
                }
                if (obj.OfficialLetters.NumOfInternships == 0)
                {
                    return RedirectToAction("noooope");

                }


                var student = _dbContext.Students.FirstOrDefault(s => s.StudentId == obj.OfficialLetters.StudentId);
                if (student != null)
                {
                    if (student.OfficialLetterStatus.ToLower() == "n/a")
                    {
                        student.OfficialLetterStatus = "pending";
                    }

                    else
                    {
                        return NotFound();
                    }

                    if (student.User.Status == "approved")
                    {
                        student.User.Status = "official-letter-requsted";
                    }
                   
                    else
                    {
                        return NotFound();
                    }

                 
                }
                _unitOfWork.Save();



                var student2 = _dbContext.Students.FirstOrDefault(s => s.StudentId == obj.OfficialLetters.StudentId);

                if (student2 != null)
                {
                    student2.OfficialLetterId = obj.OfficialLetters.Id.ToString();
                 

                    _dbContext.SaveChanges();
                }
                return RedirectToAction("Success");
            }
            return View(obj);
        }

    }
}

InternshipAutomationSystem/Areas/User/Controllers/HomeController.cs
using Internship.DataAccess.Data;
using Internship.DataAccess.Repository.IRepository;
using Internship.Models;
using Internship.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace InternshipAutomationSystem.Areas.User.Controllers
{
    [Area("User")]

    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _env;

        public HomeController(ILogger<HomeController> logger, IUnitOfWork unitOfWork, IWebHostEnvironment env)
        {

            _logger = logger;
            _unitOfWork = unitOfWork;
            _env = env;
        }
        public IActionResult Index()
        {
            return Redirect("/Identity/Account/Login");
        }

        public IActionResult Support()
        {
            return View();
        }

        public IActionResult Guide()
        {
            return View();
        }

        public IActionResult InternshipOP()
        {
            return RedirectToAction("Index", "Internshipjob");

        }
        public IActionResult Internship()
        {

            SaveandinternshipVM mymodel = new SaveandinternshipVM();
            mymodel.InternshipOpportunity = _unitOfWork.InternshipOpportunities.GetAll();
            
            return View(mymodel);

        
        }
        public IActionResult Details(int id)
        {
           
            var internship = GetInternshipById(id);

            if (internship == null)
            {
                return NotFound();
            }

            return View(internship);
        }

        public IActionResult GetInternshipDetails(int id)
        {

            var internship = GetInternshipById(id);


            return Json(internship);
        }

        private InternshipOpportunity GetInternshipById(int id)
        {
            var internship = _unitOfWork.InternshipOpportunities.GetFirstOrDefault(i => i.Id == id);

            return internship;
        }
    }
}

InternshipAutomationSystem/Areas/Student/Views/Home/Forms.cshtml
@model Internship.Models.ViewModels.FormspageVM

@using Internship.DataAccess.Data;
@using Internship.Utility;
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using Microsoft.AspNetCore.Identity
@using System.Security.Claims


@inject UserManager<ApplicationUser> UserManager

@inject ApplicationDbContext DbContext

@{
    // Get the currently signed-in user
    ApplicationUser user2 = await UserManager.GetUserAsync(User);

    // Get the associated Student_User record from the Student_User table
    Student_User studentUser = DbContext.Students.FirstOrDefault(s => s.UserId == user2.Id);

    // Access the name of the student user
    string user2status = user2?.Status;
    string studentTableStatus = studentUser?.Status;
    string studentOfficialLetter = studentUser?.OfficialLetterId ?? string.Empty;

}


<!DOCTYPE html>

<html>

<head>
    <link rel="icon" href="img/webIcon.png">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Account</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="~/css/Style.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/forms.css" asp-append-version="true" />
  

</head>

<body>
  

           
                   

                <section class="Account-Content">
                    <div class="Files">

            <div class="file1">
                <h3 class="title">Internship Application</h3>
                <p class="text">
                    The identity information of our student *, who will perform her/his internship/practice in your institution, is below within the framework of the principles set out in the Üsküdar University Associate,
                </p>
                <p class="deadline">Deadline : 31/09/2023</p>
                <div class="FilesLinks">
                    <a href="#">
                        <img src="img\support-symbol.png" alt="">
                    </a>
                    @*                <a id="LinkStartButton" asp-action="ApplicationForm_Final_Upsert" asp-area="Student" asp-controller="Application">Send the file</a>

                    *@
                    @if (true)
                    {
                        var user = await UserManager.GetUserAsync(User);

                        if (user.Status.ToLower() == "notyet" && studentTableStatus.ToLower() != "pending")
                        {
                            <a id="LinkStartButton" asp-action="SubmitForm" asp-area="Student" asp-controller="Application">Start</a>

                        }

                        else if (user.Status.ToLower() == "filled")
                        {
                            <a id="LinkStartButton" asp-action="ApplicationForm_Final_Upsert" asp-area="Student" asp-controller="Application">Send the file</a>

                        }
                        else
                        {
                            <a id="LinkStartButton" style="" asp-action="Application_Form_View" asp-area="Student" asp-controller="Application">View Your Application</a>

                        }
                    }





                </div>
            </div>

            <div class="file2">
                <h3 class="title">Letter Request</h3>
                <p class="text">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam dolorum iste
                    accusantium provident aliquam rem saepe, maxime numquam.
                </p>
                <p class="deadline">Deadline : 31/09/2023</p>
                <div class="FilesLinks">
                    <a href="#">
                        <img src="img\support-symbol.png" alt="">
                    </a>
                    @if (true)
                    {
                        var user = await UserManager.GetUserAsync(User);

                        @if (studentTableStatus.ToLower() == "pending" || user.Status.ToLower() == "notyet")

                        {
                            <a id="LinkStartButton">Nope Not yet</a>

                        }
                        else if (user2status.ToLower() == "applicationsubmit")
                        {
                            <a id="LinkStartButton" asp-action="Letter_Upsert" asp-area="Student" asp-controller="Officialletter">Start</a>
                        }

                        else if (!string.IsNullOrEmpty(studentOfficialLetter))
                        {
                            <a id="LinkStartButton">You already submitted</a>

                        }
                        else
                        {
                            <a id="LinkStartButton" asp-action="Letter_Upsert" asp-area="Student" asp-controller="Officialletter">Start</a>

                        }


                    }
                </div>
            </div>

            <div class="file3">
                <h3 class="title">Final Report</h3>
                <p class="text">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam dolorum iste
                    accusantium provident aliquam rem saepe, maxime numquam.
                </p>
                <p class="deadline">Deadline : 31/09/2023</p>
                <div class="FilesLinks">
                    @if (true)
                    {
                        <a id="LinkStartButton" asp-action="Report_Upsert" asp-area="Student" asp-controller="Application">Submit</a>

                        <a id="LinkStartButton" asp-action="Report_Download" asp-area="Student" asp-controller="Application">Download</a>
                    }
                </div>
            </div>

                    </div>
                   
                </section>


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script src="JS/app.js"></script>
</body>

</html>

InternshipAutomationSystem/Areas/Student/Views/Home/Index.cshtml
@using Internship.DataAccess.Data;
@using Microsoft.AspNetCore.Identity;
@using System.Linq


@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model Internship.Models.ViewModels.SaveandinternshipVM


@inject ApplicationDbContext DbContext
@inject UserManager<ApplicationUser> UserManager
@{
    // Get the currently signed-in user
    ApplicationUser user2 = await UserManager.GetUserAsync(User);

    // Get the associated Student_User record from the Student_User table
    Student_User studentUser = DbContext.Students.FirstOrDefault(s => s.UserId == user2.Id);

   

    }

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<head>
    <link rel="stylesheet" href="~/css/Style.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Student.css" asp-append-version="true" />

    <title>Saved Internship</title>
    <style>
        .savebutton{
            z-index:1;
        }

       
    </style>
</head>

<section class="studentpage">

    <div class="internshipSide">
        <div class="checkAll">
            <h2>Internship Oppoptunity</h2>
            <a href="#">Check all &#x2192;</a>
        </div>
        <div class="internships">
         
            @foreach (var Internship in Model.InternshipOpportunity.OrderByDescending(p => p.DatePosted).ToList().Take(3))
            {
                <div  class="firstInternship">
                    <a asp-action="Internship" asp-area="User" asp-controller="Home">
                        

                        <div class="companySave">
                            
                            <div class="companyLogo">
                                <img src="@Internship.ImageUrl" alt="" width="36px" height="36">
                                <h3>@Internship.CompanyName</h3>
                            </div>
                            <form method="post" asp-controller="Home" asp-action="SaveInternship">

                                <input hidden name="id" value="@Internship.Id" />
                                <input hidden name="id" asp-for="@Model.SavedInternships.Id" />
                                <button type="submit">

                                  
                                 
                                        <img src="~/img/save-symbol.png" alt="" width="24px" height="30">
                               

                               
                            </button>
                            </form>
                        </div>
                        <div class="job">
                            <h3>@Internship.JobTitle</h3>
                            <h5>@Internship.type</h5>
                        </div>
                        <div class="location">
                            <img src="~/img\location-symbol.png" alt="">
                            <h5>@Internship.Location</h5>
                        </div>
                    </a>
                </div>
    }
           


          
        </div>
    </div>
    <div class="howWork">
        <div class="how">
            <h2>How the system work?</h2>
        </div>
        <div class="steps">
            <div class="step1">
                <div class="step1-content">
                    <h3>Step 1</h3>
                    <p>
                        Fill Out the application form and sign it
                        from the institution you are going to work with
                    </p>
                    <button>Button</button>
                </div>
            </div>
            <div class="step1">
                <div class="step1-content">
                    <h3>Step 2</h3>
                    <p>
                        Submit all the forms and wait for the approval from your instructor<br />
                        <i>#you can follow your application status from the status bar up there</i>
                    </p>
                    <button>Button</button>
                </div>
            </div>

            <div class="step1">
                <div class="step1-content">
                    <h3>Step 3</h3>
                    <p>
                        Fill Out the application form and sign it
                        from the institution you are going to work with
                    </p>
                    <button>Button</button>
                </div>
            </div>
        </div>
    </div>

</section>

InternshipAutomationSystem/Areas/Student/Views/Home/View_Saved_Internship.cshtml
@using Internship.DataAccess.Data;
@using Microsoft.AspNetCore.Identity;
@model IEnumerable<SavedInternship>

@inject ApplicationDbContext DbContext
@inject UserManager<ApplicationUser> UserManager
@{
    // Get the currently signed-in user
    ApplicationUser user2 = await UserManager.GetUserAsync(User);

    // Get the associated Student_User record from the Student_User table
    Student_User studentUser = DbContext.Students.FirstOrDefault(s => s.UserId == user2.Id);
    int studentId = studentUser.StudentId;

    }
<head>
    <link rel="icon" href="~/img/webIcon.png">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Saved Internships</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/css/savedinternship.css" rel="stylesheet" />
    <link href="~/css/account.css" rel="stylesheet" />
    <link href="~/css/student.css" rel="stylesheet" />

  
</head>


<div class="Account-Content">
    <div class="Account-Links">
        <a asp-area="Identity" asp-page="/Account/Manage/Index"> My profile</a>
        <a href="AccountStatus.html">Status</a>
        <a asp-area="Student" asp-action="Report_View" asp-controller="Application">Health Insurance</a>
        <a id="selected" href="SavedInternships.html">Saved Internships</a>
    </div>

    <div id="line"></div>


    <div class="right-side-panel">
        <div class="MyProfile">

            <h3>Saved Internships</h3>

        </div>
        <div class="SavedInternships">

            @foreach (var Internship in Model.Where(i => i.StudentId == @studentId).ToList())
            {
                <div class="firstInternship2">
                    <a asp-action="Internship" asp-area="User" asp-controller="Home">


                        <div class="companySave">

                            <div class="companyLogo">
                                <img src="@Internship.InternshipOpportunity.ImageUrl" alt="" width="36px" height="36">
                                <h3>@Internship.InternshipOpportunity.CompanyName</h3>
                            </div>

                        </div>
                        <div class="job">
                            <h3>@Internship.InternshipOpportunity.JobTitle</h3>
                            <h5>@Internship.InternshipOpportunity.type</h5>
                        </div>
                        <div class="location">
                            <img src="img\location-symbol.png" alt="">
                            <h5>@Internship.InternshipOpportunity.Location</h5>
                        </div>
                    </a>
                </div>
            }

        </div>
    </div>
   

</div>