InternshipAutomationSystem/Areas/CareerCenter/Controllers/AnnouncementsController.cs
using Internship.DataAccess.Repository.IRepository;
using Internship.Models;
using Internship.Models.ViewModels;
using Internship.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Data;

namespace InternshipAutomationSystem.Areas.CareerCenter.Controllers
{ 
    
    [Area("CareerCenter")]
    [Authorize(Roles = SD.Role_Career_Center)]

    public class AnnouncementsController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IUnitOfWork _unitOfWork;
            private readonly IWebHostEnvironment _HostEnvironment;
            public AnnouncementsController(UserManager<ApplicationUser> userManager , IUnitOfWork unitOfWork, IWebHostEnvironment hostEnvironment)
            {
            _userManager = userManager;
            _unitOfWork = unitOfWork;
                _HostEnvironment = hostEnvironment;
            }
            public IActionResult Announcement()
            {
            IEnumerable<Announcement> AnnouncementList = _unitOfWork.Announcements.GetAll();
             return View(AnnouncementList);
             }

     





        public IActionResult Upsert_Announcement(int? Id)
        {
            AnnouncementVM AnnouncementVM = new()
            {
                Announcements = new(),


            };
            if (Id == null || Id == 0)
            {
                return View(AnnouncementVM);
            }
            else
            {
                AnnouncementVM.Announcements = _unitOfWork.Announcements.GetFirstOrDefault(u => u.Id == Id);
                return View(AnnouncementVM);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert_Announcement(AnnouncementVM obj)
        {
            if (ModelState.IsValid)
             {
               
               
                if (obj.Announcements.Id == 0)
                {
                  
                    _unitOfWork.Announcements.Add(obj.Announcements);
                }
                else
                {
                    _unitOfWork.Announcements.Update(obj.Announcements);
                }

                _unitOfWork.Save();
                return RedirectToAction("Index", "CareerCenter");
            }

            return View(obj);
        }


        public IActionResult Delete(int? Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }

            return View();

        }

        #region API CALLS
     

        [HttpPost]
        public IActionResult DeletePost_Announcement(int? Id)
        {
            var obj = _unitOfWork.Announcements.GetFirstOrDefault(u => u.Id == Id);

            if (obj == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }

          
         

            _unitOfWork.Announcements.Remove(obj);
            _unitOfWork.Save();

            return Json(new { success = true, message = "Internship deleted successfully" });

        }


        #endregion


    }


}

InternshipAutomationSystem/Areas/CareerCenter/Controllers/CareercenterController.cs
using Internship.DataAccess.Data;
using Internship.DataAccess.Repository.IRepository;
using Internship.Models;
using Internship.Models.ViewModels;
using Internship.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Data;
using System.Security.Policy;

namespace InternshipAutomationSystem.Areas.CareerCenter.Controllers
{
    [Area("CareerCenter")]
    [Authorize(Roles = SD.Role_Career_Center)]
    public class CareercenterController : Controller
    {
        private readonly ApplicationDbContext _dbContext;
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _HostEnvironment;
        public CareercenterController(IUnitOfWork unitOfWork, IWebHostEnvironment hostEnvironment, ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;

            _unitOfWork = unitOfWork;
            _HostEnvironment = hostEnvironment;
        }
        public IActionResult Index()
        {
            IEnumerable<Student_User> students = _unitOfWork.Students.GetAll();

            var applicationFormsList = students.Select(student => new HealthInsurance
            {
                Student = student,
                StudentId = student.StudentId,
                Id = student.HealthInsuranceId != null ? int.Parse(student.HealthInsuranceId) : 0,
                HealthInsurancePDF = student.HealthInsurance != null ? student.HealthInsurance.HealthInsurancePDF : null,
            }); ;

            return View(applicationFormsList);
        }

        public IActionResult Health_Insurance_Approval()
        {

            IEnumerable<Student_User> students = _unitOfWork.Students.GetAll();

            var applicationFormsList = students.Select(student => new HealthInsurance
            {
                Student = student,
                StudentId = student.StudentId,
                Id = student.HealthInsuranceId != null ? int.Parse(student.HealthInsuranceId) : 0,
                HealthInsurancePDF = student.HealthInsurance != null ? student.HealthInsurance.HealthInsurancePDF : null,
            }); ;

            return View(applicationFormsList);
        }

        public IActionResult Old_Health_Insurance_Approval()
        {

            IEnumerable<Student_User> students = _unitOfWork.Students.GetAll();

            var applicationFormsList = students.Select(student => new HealthInsurance
            {
                Student = student,
                StudentId = student.StudentId,
                Id = student.HealthInsuranceId != null ? int.Parse(student.HealthInsuranceId) : 0,
                HealthInsurancePDF = student.HealthInsurance != null ? student.HealthInsurance.HealthInsurancePDF : null,
            }); ;

            return View(applicationFormsList);
        }

        public IActionResult Health_Upsert(int? Id)
        {

            HealthVM HealthVM = new()
            {
                HealthInsurances = new(),

                StudentList = _unitOfWork.Students.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.StudentId.ToString(),
                    Selected = i.HealthInsuranceId != null
                }),
                CareerCenterList = _unitOfWork.CareerCenters.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString(),

                }),

            };


            if (Id == null || Id == 0)
            {
                return View(HealthVM);
            }

            else
            {
                HealthVM.HealthInsurances = _unitOfWork.HealthInsurances.GetFirstOrDefault(u => u.Id == Id);
                return View(HealthVM);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Health_Upsert(HealthVM obj, IFormFile file)
        {


            if (ModelState.IsValid)
            {
                if (obj.HealthInsurances.Id != 0)
                {
                    obj.HealthInsurances.HealthInsurancePDF = _unitOfWork.HealthInsurances.GetFirstOrDefault(u => u.Id == obj.HealthInsurances.Id).HealthInsurancePDF;
                    obj.HealthInsurances.Student = _unitOfWork.HealthInsurances.GetFirstOrDefault(u => u.Id == obj.HealthInsurances.Id).Student;
                    obj.HealthInsurances.CareerCenter = _unitOfWork.HealthInsurances.GetFirstOrDefault(u => u.Id == obj.HealthInsurances.Id).CareerCenter;
                }

                string wwwRootPath = _HostEnvironment.WebRootPath;

                if (file != null)
                {
                    string fileName = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(wwwRootPath, @"PDFCAN\Health_Insurance");
                    var extension = Path.GetExtension(file.FileName);

                    if (obj.HealthInsurances.Id != 0)
                    {
                        var oldFilePath = Path.Combine(wwwRootPath, obj.HealthInsurances.HealthInsurancePDF.TrimStart('\\'));
                        if (System.IO.File.Exists(oldFilePath)) 
                        {
                            System.IO.File.Delete(oldFilePath);
                        }
                    }
                    using (var fileStream = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                    {
                        file.CopyTo(fileStream);
                    }
                    obj.HealthInsurances.HealthInsurancePDF = @"PDFCAN\Health_Insurance\" + fileName + extension;

                    // Update the Status property for the student
                    var student = _dbContext.Students.FirstOrDefault(s => s.StudentId == obj.HealthInsurances.StudentId);
                    if (student != null)
                    {
                        Student_User studentUser = _dbContext.Students
                            .Include(s => s.User)
                            .FirstOrDefault(s => s.UserId == student.UserId);

                        if (studentUser.HealthInsuranceStatus.ToLower() == "pending")
                        {
                            studentUser.HealthInsuranceStatus = "completed";
                           
                        }
                        else
                        {
                            return NotFound();
                        }
                        if (studentUser.User.Status == "approved")
                        {
                            studentUser.User.Status = "health_insurance";
                        }
                        else if (studentUser.User.Status == "official-letter")
                        {
                            studentUser.User.Status = "health-letter";
                        }
                    }
                    else
                    {
                        return NotFound();
                    }


                }
                

                if (obj.HealthInsurances.Id == 0)
                {
                    _unitOfWork.HealthInsurances.Add(obj.HealthInsurances);
                }
                else
                {
                    _unitOfWork.HealthInsurances.Update(obj.HealthInsurances);
                }
                _unitOfWork.Save();

                var student2 = _dbContext.Students.FirstOrDefault(s => s.StudentId == obj.HealthInsurances.StudentId);

                if (student2 != null)
                {
                    student2.HealthInsuranceId = obj.HealthInsurances.Id.ToString();

                    _dbContext.SaveChanges();
                }
               
                return RedirectToAction("Success");
            }
            return View(obj);
        }

        public IActionResult Success()
        {
            return View();
        }


    }
}

InternshipAutomationSystem/Areas/CareerCenter/Controllers/InternshipController.cs
using Internship.DataAccess.Repository.IRepository;
using Internship.Models.ViewModels;
using Internship.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace InternshipAutomationSystem.Areas.CareerCenter.Controllers
{ 
    
    [Area("CareerCenter")]
    [Authorize(Roles = SD.Role_Career_Center)]

    public class InternshipController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
            private readonly IWebHostEnvironment _HostEnvironment;
            public InternshipController(IUnitOfWork unitOfWork, IWebHostEnvironment hostEnvironment)
            {
                _unitOfWork = unitOfWork;
                _HostEnvironment = hostEnvironment;
            }
            public IActionResult Index()
        {
            return View();
        }

        public IActionResult Upsert_Internship(int? Id)
        {
            InternshipVM InternshipVM = new()
            {
                InternshipOpportunities = new(),


            };
            if (Id == null || Id == 0)
            {
                return View(InternshipVM);
            }
            else
            {
                InternshipVM.InternshipOpportunities = _unitOfWork.InternshipOpportunities.GetFirstOrDefault(u => u.Id == Id);
                return View(InternshipVM);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert_Internship(InternshipVM obj, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                string wwwRootPath = _HostEnvironment.WebRootPath;
                if (file != null)
                {
                    string fileName = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(wwwRootPath, @"Images\InternshipJobs");
                    var extension = Path.GetExtension(file.FileName);

                    if (obj.InternshipOpportunities.ImageUrl != null)
                    {
                        var oldImagePath = Path.Combine(wwwRootPath, obj.InternshipOpportunities.ImageUrl.TrimStart('\\'));
                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }
                    using (var fileStreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                    {
                        file.CopyTo(fileStreams);
                    }
                    obj.InternshipOpportunities.ImageUrl = @"\Images\InternshipJobs\" + fileName + extension;
                }
                if (obj.InternshipOpportunities.Id == 0)
                {
                    _unitOfWork.InternshipOpportunities.Add(obj.InternshipOpportunities);
                }
                else
                {
                    _unitOfWork.InternshipOpportunities.Update(obj.InternshipOpportunities);
                }


                _unitOfWork.Save();
                return RedirectToAction("Index","CareerCenter");
            }
            return View(obj);
        }

        public IActionResult Delete(int? Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }

            return View();

        }

        #region API CALLS
        [HttpGet]
        public IActionResult GetAll_Internship()
        {
            var InternshipList = _unitOfWork.InternshipOpportunities.GetAll();
            return Json(new { data = InternshipList });
        }

        [HttpPost]
        public IActionResult DeletePost_Internship(int? Id)
        {
            var obj = _unitOfWork.InternshipOpportunities.GetFirstOrDefault(u => u.Id == Id);

            if (obj == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }

            var oldImagePath = Path.Combine(_HostEnvironment.WebRootPath, obj.ImageUrl.TrimStart('\\'));
            if (System.IO.File.Exists(oldImagePath))
            {
                System.IO.File.Delete(oldImagePath);
            }

            _unitOfWork.InternshipOpportunities.Remove(obj);
            _unitOfWork.Save();

            return Json(new { success = true, message = "Internship deleted successfully" });

        }


        #endregion


    }


}

InternshipAutomationSystem/Areas/CareerCenter/Views/Careercenter/Health_Insurance_Approval.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@using Internship.Models;
@using Internship.Utility;
@model IEnumerable<HealthInsurance>



<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Application Form Approval</title>

    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="~/Css/CareerCenter.css">
    <link rel="stylesheet" href="~/Css/DataTable.css">
    <link rel="stylesheet" href="~/Css/Style.css">
    <link rel="stylesheet" href="~/Css/form.css">
</head>

<div class="back">
    <a asp-action="Index" asp-controller="Careercenter" id="back">
        <h4> <-- Back </h4>
    </a>
</div>
<div class="table-container" style="    background: #fff;
    padding: 2rem;
    border-radius: 27px;">
    <h3>Application Form Approval</h3>
    <div class="widgetHeader">

        <div class="search">
            <input type="text" id="searchInput" placeholder="Search...">
        </div>

    </div>
    <div class="DataTable">


        <table id="studentTable">
            <thead>
                <tr>
                    <th onclick="sortTable(0)">
                        Student Name

                        <img id="nameSort" class="sort rotateImage"
                             src="img/CareerCenter/arrowUp.png" alt="">
                    </th>

                    <th onclick="sortTable(1)">
                        Student ID

                        <img class="sort rotateImage" id="idSort"
                             src="img/CareerCenter/arrowUp.png" alt="">

                    </th>

                    <th onclick="sortTable(2)">
                        State
                        <img id="stateSort" class="sort rotateImage"
                             src="img/CareerCenter/arrowUp.png" alt="">
                    </th>
                    <th class="center">Upload</th>

                </tr>
            </thead>
            <tbody>
                @foreach (var applicationForm in Model)
                {
                    <tr>
                        <td>@applicationForm.Student.Name</td>

                        <td>@applicationForm.Student.StudentId</td>

                        <td class="center state @(applicationForm.Student.HealthInsuranceStatus.ToLower() == "pending" ? "pending" : (applicationForm.Student.HealthInsuranceStatus.ToLower() == "completed" ? "completed" : "NA"))">
                            <div>@(applicationForm.Student.HealthInsuranceStatus.ToLower() == "pending" ? "Pending" : (applicationForm.Student.HealthInsuranceStatus.ToLower() == "completed" ? "completed" : "N/A"))</div>
                        </td>

                        <td class="center">
                            @if (applicationForm.Student.HealthInsuranceStatus.ToLower() == "pending")
                            {
                                <a class="edit" href="/CareerCenter/Careercenter/Health_Upsert?id=@applicationForm.Id">
                                    <img src="~/img/upload.png" height="20px">
                                </a>

                                <a href="@Url.Action("Application_Form_View", "Careercenter", new { applicationFormId = applicationForm.Id })" style="margin-left:1rem;">
                                    <img src="~/img/eye-symbol.png" height="20px" alt="View" class="upload-icon">
                                </a>
                            }
                            else if (applicationForm.Student.HealthInsuranceStatus.ToLower() == "n/a")
                            {
                                <span>Not Submitted</span>
                            }
                           
                        </td>

                    </tr>
                }
            </tbody>

        </table>

    </div>

InternshipAutomationSystem/Areas/CareerCenter/Views/Careercenter/Health_Upsert.cshtml
@model Internship.Models.ViewModels.HealthVM

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers


<!DOCTYPE html>
<html>
<head>
    <title>Application Form</title>

    <link rel="stylesheet" href="~/css/DataTable.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/form.css" asp-append-version="true" />
</head>
<body>
    <h1>Application Form</h1>

    <form method="post" class="WebForm" asp-action="Health_Upsert" enctype="multipart/form-data">
        <input asp-for="@Model.HealthInsurances.Id" hidden />

        <div>
            <label for="@Model.HealthInsurances.HealthInsurancePDF"></label>
            <input asp-for="@Model.HealthInsurances.HealthInsurancePDF" type="file" name="file" placeholder="ImageUrl" />
        </div>


        <div  class="inputQue">
            <label>Student</label>
            <select asp-for="@Model.HealthInsurances.StudentId" asp-items="@Model.StudentList" class="selectC">
                <option disabled selected>Select Student</option>
            </select>
            <span asp-validation-for="@Model.HealthInsurances.StudentId" class="alert-warning"></span>

        </div>

        <div  class="inputQue">
            <label>CareerCenter</label>
            <select asp-for="@Model.HealthInsurances.CareerCenterId" asp-items="@Model.CareerCenterList" class="selectC">
                <option disabled selected>Select CareerCenter</option>
            </select>
            <span asp-validation-for="@Model.HealthInsurances.CareerCenterId" class="alert-warning"></span>

        </div>

        <button type="submit">Submit</button>
    </form>
</body>
</html>

InternshipAutomationSystem/Areas/CareerCenter/Views/Careercenter/Index.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@model IEnumerable<HealthInsurance>


@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<head>
    <link rel="stylesheet" href="~/css/CareerCenter.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/DataTable.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/form.css" asp-append-version="true" />

</head>

<div id="back-buttons"></div>

<section class="CareerCenter-Content">

    <div class="left-section both-sides">
        <div class="widget-left-side widgets-shared">

            <div class="widgetHeader">
                <div class="Icon-text">
                    <img src="~/img/CareerCenter/HealthInsurance.png" height="45px" alt="">
                    <p>Health Insurance</p>
                </div>
                <div class="check-all-btn">
                    <a asp-action="Health_Insurance_Approval" asp-controller="Careercenter" id="check-all">Check all &#x2192;</a>
                    <input type="text" id="searchInput" placeholder="Search...">
                </div>

            </div>
            <div class="DataTable2">

                <table id="studentTable">
                    <thead>
                        <tr>
                            <th class="indexth-student" onclick="sortTable(0)">
                                Student Name

                                <img id="nameSort" class="sort rotateImage"
                                     src="~/img/CareerCenter/arrowUp.png" alt="">
                            </th>

                            <th class="indexth-student" onclick="sortTable(1)">
                                Student ID

                                <img class="sort rotateImage" id="idSort"
                                     src="~/img/CareerCenter/arrowUp.png" alt="">

                            </th>

                            <th class="indexth" onclick="sortTable(2)">
                                State
                                <img id="stateSort" class="sort rotateImage"
                                     src="~/img/CareerCenter/arrowUp.png" alt="">
                            </th>
                          @*  <th class="center">Upload</th>*@
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var applicationForm in Model.Take(4))
                        {
                            <tr>
                                <td>@applicationForm.Student.Name</td>

                                <td>@applicationForm.Student.StudentId</td>

                                <td class="center state @(applicationForm.Student.HealthInsuranceStatus.ToLower() == "pending" ? "pending" : (applicationForm.Student.HealthInsuranceStatus.ToLower() == "completed" ? "completed" : "NA"))">
                                    <div>@(applicationForm.Student.HealthInsuranceStatus.ToLower() == "pending" ? "Pending" : (applicationForm.Student.HealthInsuranceStatus.ToLower() == "completed" ? "completed" : "N/A"))</div>
                                </td>

                               

                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <div id="right-widgets" class="right-section-widgets both-sides">

      

        <a asp-action="Old_Health_Insurance_Approval"  asp-controller="CareerCenter" class="widgets-shared" id="widget2">
            <div id="old-HealthI-btn" class="widget-right-side">
                <p>Old Health Insurance</p>
                <img src="~/img/CareerCenter/HealthInsurance.png" height="45px" alt="">
            </div>

            
        </a>

        
        <a asp-controller="Announcements" asp-action="Upsert_Announcement" class="widgets-shared" id="widget4">
            <div id="Add-Announcement-btn" class="widget-right-side">
                <p>Add New Announcement</p>
                <img src="~/img/CareerCenter/Notification.png" height="45px" alt="">
            </div>
        </a>


        <a asp-controller="Internship" asp-action="Upsert_Internship" class="widgets-shared" id="widget4">
            <div  class="widget-right-side">
                <p>Add Internship opportunity</p>

                <img src="~/img/CareerCenter/SuitCase.png" height="45px" alt="">
            </div>

        </a>

    </div>
</section>



<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
<script src="~/JS/app.js"></script>

InternshipAutomationSystem/Areas/CareerCenter/Views/Careercenter/Old_Health_Insurance_Approval.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@using Internship.Models;
@using Internship.Utility;
@model IEnumerable<HealthInsurance>



<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Application Form Approval</title>

    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="~/Css/CareerCenter.css">
    <link rel="stylesheet" href="~/Css/DataTable.css">
    <link rel="stylesheet" href="~/Css/Style.css">
    <link rel="stylesheet" href="~/Css/form.css">
</head>

<div class="back">
    <a asp-action="Index" asp-controller="Careercenter" id="back">
        <h4> <-- Back </h4>
    </a>
</div>
<div class="table-container" style="    background: #fff;
    padding: 2rem;
    border-radius: 27px;">
    <h3>Application Form Approval</h3>
    <div class="widgetHeader">

        <div class="search">
            <input type="text" id="searchInput" placeholder="Search...">
        </div>

    </div>
    <div class="DataTable">


        <table id="studentTable">
            <thead>
                <tr>
                    <th onclick="sortTable(0)">
                        Student Name

                        <img id="nameSort" class="sort rotateImage"
                             src="img/CareerCenter/arrowUp.png" alt="">
                    </th>

                    <th onclick="sortTable(1)">
                        Student ID

                        <img class="sort rotateImage" id="idSort"
                             src="img/CareerCenter/arrowUp.png" alt="">

                    </th>

                    <th onclick="sortTable(2)">
                        State
                        <img id="stateSort" class="sort rotateImage"
                             src="img/CareerCenter/arrowUp.png" alt="">
                    </th>
                    <th class="center">Upload</th>

                </tr>
            </thead>
            <tbody>
                @foreach (var applicationForm in Model.Where(form => form.Student.HealthInsuranceStatus.ToLower() == "completed"))
                {
                    <tr>
                        <td>@applicationForm.Student.Name</td>

                        <td>@applicationForm.Student.StudentId</td>

                        <td class="center state @(applicationForm.Student.HealthInsuranceStatus.ToLower() == "pending" ? "pending" : (applicationForm.Student.HealthInsuranceStatus.ToLower() == "completed" ? "completed" : "NA"))">
                            <div>@(applicationForm.Student.HealthInsuranceStatus.ToLower() == "pending" ? "Pending" : (applicationForm.Student.HealthInsuranceStatus.ToLower() == "completed" ? "completed" : "N/A"))</div>
                        </td>

                        <td class="center">
                            @if (applicationForm.Student.HealthInsuranceStatus.ToLower() == "pending")
                            {
                                <a class="edit" href="/CareerCenter/Careercenter/Health_Upsert?id=@applicationForm.Id">
                                    <img src="~/img/upload.png" height="20px">
                                </a>

                                <a href="@Url.Action("Application_Form_View", "Careercenter", new { applicationFormId = applicationForm.Id })" style="margin-left:1rem;">
                                    <img src="~/img/eye-symbol.png" height="20px" alt="View" class="upload-icon">
                                </a>
                            }
                            else if (applicationForm.Student.HealthInsuranceStatus.ToLower() == "n/a")
                            {
                                <span>Not Submitted</span>
                            }

                        </td>

                    </tr>
                }
            </tbody>

        </table>

    </div>

InternshipAutomationSystem/Areas/CareerCenter/Views/Careercenter/Success.cshtml
<head>
    <link rel="icon" href="img/webIcon.png">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Success</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/css/success.css" rel="stylesheet" />
    <link href="~/css/style.css" rel="stylesheet" />
    <link rel="stylesheet" href=".css">

</head>


<section class="Account-Content">
    <div class="success-box" id="popup-div">
        <img src="~/img/support-symbol-selected.png" class="img2">
        <h1>Successfully submitted</h1>
        <div class="alert-btns">
           

            <a asp-action="Index" asp-controller="Careercenter" class="yes btn" type="submit" id="Ok">Ok</a>
          
        </div>
    </div>

</section>